@LibraryManagment_HostAddress = https://localhost:7237

POST {{LibraryManagment_HostAddress}}/api/Auth/login
Content-Type: application/json

{
  "username": "your_test_user",
  "password": "your_password"
}